# Generated by Django 3.0.6 on 2020-10-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_indexgalleryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexGalleryImage',
        ),
    ]
